//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TechDays2012DemoModel", "FK_ClassProperties_Classes", "Classes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(T4_EntityFramework_Custom_Aspect.Class), "ClassProperties", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(T4_EntityFramework_Custom_Aspect.ClassProperty), true)]

#endregion

namespace T4_EntityFramework_Custom_Aspect
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TechDays2012DemoEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TechDays2012DemoEntities object using the connection string found in the 'TechDays2012DemoEntities' section of the application configuration file.
        /// </summary>
        public TechDays2012DemoEntities() : base("name=TechDays2012DemoEntities", "TechDays2012DemoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TechDays2012DemoEntities object.
        /// </summary>
        public TechDays2012DemoEntities(string connectionString) : base(connectionString, "TechDays2012DemoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TechDays2012DemoEntities object.
        /// </summary>
        public TechDays2012DemoEntities(EntityConnection connection) : base(connection, "TechDays2012DemoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Class> Classes
        {
            get
            {
                if ((_Classes == null))
                {
                    _Classes = base.CreateObjectSet<Class>("Classes");
                }
                return _Classes;
            }
        }
        private ObjectSet<Class> _Classes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ClassProperty> ClassProperties
        {
            get
            {
                if ((_ClassProperties == null))
                {
                    _ClassProperties = base.CreateObjectSet<ClassProperty>("ClassProperties");
                }
                return _ClassProperties;
            }
        }
        private ObjectSet<ClassProperty> _ClassProperties;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Classes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClasses(Class @class)
        {
            base.AddObject("Classes", @class);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ClassProperties EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClassProperties(ClassProperty classProperty)
        {
            base.AddObject("ClassProperties", classProperty);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TechDays2012DemoModel", Name="Class")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Class : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Class object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="className">Initial value of the ClassName property.</param>
        public static Class CreateClass(global::System.Int64 id, global::System.String className)
        {
            Class @class = new Class();
            @class.ID = id;
            @class.ClassName = className;
            return @class;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClassName
        {
            get
            {
                return _ClassName;
            }
            set
            {
                OnClassNameChanging(value);
                ReportPropertyChanging("ClassName");
                _ClassName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClassName");
                OnClassNameChanged();
            }
        }
        private global::System.String _ClassName;
        partial void OnClassNameChanging(global::System.String value);
        partial void OnClassNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TechDays2012DemoModel", "FK_ClassProperties_Classes", "ClassProperties")]
        public EntityCollection<ClassProperty> ClassProperties
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ClassProperty>("TechDays2012DemoModel.FK_ClassProperties_Classes", "ClassProperties");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ClassProperty>("TechDays2012DemoModel.FK_ClassProperties_Classes", "ClassProperties", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TechDays2012DemoModel", Name="ClassProperty")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ClassProperty : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ClassProperty object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="classID">Initial value of the ClassID property.</param>
        /// <param name="propertyName">Initial value of the PropertyName property.</param>
        /// <param name="propertyType">Initial value of the PropertyType property.</param>
        /// <param name="validateOnSet">Initial value of the ValidateOnSet property.</param>
        public static ClassProperty CreateClassProperty(global::System.Int64 id, global::System.Int64 classID, global::System.String propertyName, global::System.String propertyType, global::System.Boolean validateOnSet)
        {
            ClassProperty classProperty = new ClassProperty();
            classProperty.ID = id;
            classProperty.ClassID = classID;
            classProperty.PropertyName = propertyName;
            classProperty.PropertyType = propertyType;
            classProperty.ValidateOnSet = validateOnSet;
            return classProperty;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ClassID
        {
            get
            {
                return _ClassID;
            }
            set
            {
                OnClassIDChanging(value);
                ReportPropertyChanging("ClassID");
                _ClassID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClassID");
                OnClassIDChanged();
            }
        }
        private global::System.Int64 _ClassID;
        partial void OnClassIDChanging(global::System.Int64 value);
        partial void OnClassIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PropertyName
        {
            get
            {
                return _PropertyName;
            }
            set
            {
                OnPropertyNameChanging(value);
                ReportPropertyChanging("PropertyName");
                _PropertyName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PropertyName");
                OnPropertyNameChanged();
            }
        }
        private global::System.String _PropertyName;
        partial void OnPropertyNameChanging(global::System.String value);
        partial void OnPropertyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PropertyType
        {
            get
            {
                return _PropertyType;
            }
            set
            {
                OnPropertyTypeChanging(value);
                ReportPropertyChanging("PropertyType");
                _PropertyType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PropertyType");
                OnPropertyTypeChanged();
            }
        }
        private global::System.String _PropertyType;
        partial void OnPropertyTypeChanging(global::System.String value);
        partial void OnPropertyTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ValidateOnSet
        {
            get
            {
                return _ValidateOnSet;
            }
            set
            {
                OnValidateOnSetChanging(value);
                ReportPropertyChanging("ValidateOnSet");
                _ValidateOnSet = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ValidateOnSet");
                OnValidateOnSetChanged();
            }
        }
        private global::System.Boolean _ValidateOnSet;
        partial void OnValidateOnSetChanging(global::System.Boolean value);
        partial void OnValidateOnSetChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TechDays2012DemoModel", "FK_ClassProperties_Classes", "Classes")]
        public Class Class
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Class>("TechDays2012DemoModel.FK_ClassProperties_Classes", "Classes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Class>("TechDays2012DemoModel.FK_ClassProperties_Classes", "Classes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Class> ClassReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Class>("TechDays2012DemoModel.FK_ClassProperties_Classes", "Classes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Class>("TechDays2012DemoModel.FK_ClassProperties_Classes", "Classes", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
